import { ISignUpForm } from "@/components/forms/signUpForm";
import { GoogleSpreadsheet } from "google-spreadsheet";

export async function addSignUpToSpreadSheets(formValues: ISignUpForm) {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet(
    process.env.GOOGLE_SPREADSHEET_ID
  );

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || "",
    private_key: process.env.GOOGLE_PRIVATE_KEY || "",
  });

  await doc.loadInfo(); // loads document properties and worksheets
  // create a sheet and set the header row
  // const sheet = await doc.addSheet({ headerValues: ["email", "interestedAsAthlete", "interestedAsCoach", "athleteLevel", "coachLevel", "surveys"] });
  const sheet = doc.sheetsByTitle[process.env.GOOGLE_SIGNUP_SHEET_TITLE ||""];
  // append row
  const larryRow = await sheet.addRow({
    email: formValues.email,
    interestedAsAthlete: formValues.interestedAs.includes("athlete"),
    interestedAsCoach: formValues.interestedAs.includes("coach"),
    athleteLevel: formValues.athleteLevel,
    coachLevel: formValues.coachLevel,
    surveys: formValues.surveys,
  });

  // read rows
  const rows = await sheet.getRows(); // can pass in { limit, offset }
}
